### ISSUE TITLE
Helm chart no longer at https://snyk.github.io/kubernetes-monitor

### ISSUE THREAD

**Issue by paulgear** [snyk/kubernetes-monitor#566]
https://github.com/snyk/kubernetes-monitor/tree/staging/snyk-monitor states that the URL for the Helm chart should be https://snyk.github.io/kubernetes-monitor, yet this URL produces a 404.  Could the site please be fixed, or the documentation updated with the correct URL?
Thanks.

**Comment by shaimendel** [comment]
Hi @paulgear - thanks for reaching out!
the address is actually ok, the files are directly accessible - for example:
* https://snyk.github.io/kubernetes-monitor/snyk-monitor/values.yaml 
* https://snyk.github.io/kubernetes-monitor/snyk-monitor/templates/deployment.yaml

**Comment by shaimendel** [comment]
BTW - the branch that is accessible via those GitHub pages is `gh-pages` that can be seen in https://github.com/snyk/kubernetes-monitor/tree/gh-pages

**Comment by paulgear** [comment]
Hi @shaimendel - thanks for the quick response.  We were seeing errors (404s, if I remember correctly) when attempting to deploy from this chart, so I'll investigate again when I get to work tomorrow.

**Comment by shaimendel** [comment]
just to be on the safe side - making sure you have our updated docs https://support.snyk.io/hc/en-us/articles/360003916158-Install-the-Snyk-controller-with-Helm

**Comment by paulgear** [comment]
Thanks @shaimendel - we're deploying in Azure DevOps via Terraform, so we're not running kubectl & helm manually like that.  The exact error message we're seeing is:
`Error: chart "snyk-charts" version "1.32.3" not found in https://snyk.github.io/kubernetes-monitor/ repository`
Does this mean that older versions are removed from your repo as soon as they are superseded?

**Comment by shaimendel** [comment]
I managed to install now 1.32.3 (which is the latest) with `helm`. a few questions:
- do you maybe need to run the equivalent of `helm repo update` to get the latest charts before trying to install it?
- the chart name is `snyk-monitor` within that helm chart folder. that's why the helm command is `helm upgrade --install snyk-monitor snyk-chart/snyk-monitor ...`. the **snyk-chart/snyk-monitor** is the important part, do you need to specify it somewhere else? so it doesn't assume the chart is directly in snyk-chart, rather in snyk-chart/snyk-monitor

**Comment by gysiedebruyn** [comment]
@paulgear & @shaimendel it seems like this issues lies with how Terraform does the installation. I have been able to install snyk-monitor but ran into issues with our policies due to the inability to add/change existing labels. I have raised this with Loukas and Eitan directly.

I think we can close this issue.

@shaimendel just some background, @paulgear and I are colleagues and work together on the same project, this is where we encountered this issue.

**Comment by phyzical** [comment]
Incase others run into this it should just be the following

```
resource "helm_release" "snyk" {
  name             = "snyk-monitor"
  repository       = "https://snyk.github.io/kubernetes-monitor"
  chart            = "snyk-monitor"
  namespace        = "snyk-monitor"
  create_namespace = true

  values = [
    "${file("${path.module}/templates/snyk_values.yaml")}"
  ]
}
```
