### ISSUE TITLE
[🙏] Don't use mutable busybox:latest tag by default

### ISSUE THREAD

**Issue by gabegorelick** [snyk/kubernetes-monitor#968]
**Describe the user need**
I don't want my containers to break when an upstream vendor publishes a new `latest` image. I also don't want to be subject to a supply chain attack made easier by blindly pulling in a mutable container image tag.

**Describe expected behaviour**

Pin init container image to a fixed busybox tag. This is configurable by the end-user, but the chart should come out of the box with a safer value. Additionally, forcing the end-user to manage the container themselves (ensuring it's kept up to date), isn't great. 

**Additional context**

https://github.com/snyk/kubernetes-monitor/blob/3c508fb66a24cbbf410a4205e438a4d0f8f2654e/snyk-monitor/values.yaml#L40

**Comment by kat1906** [comment]
Hi @gabegorelick , thank you very much for raising this issue. I will get back to you as soon as I have discussed it with the team. 😃

**Comment by ivanstanev** [comment]
Hey @gabegorelick, changing to a specific tag won't make it less likely to be susceptible to supply chain attacks because tags are mutable. It is possible to pin to a specific SHA instead which would help prevent these types of attacks but we would have to do this for every asset that we depend on, with the tag being determined right after we push the image to the container registry (so that we understand what content digest it gets).

We have been trying to spike using image signing with `cosign` recently - https://github.com/snyk/kubernetes-monitor/pull/953. Would that be something that can give you more confidence in using the images instead of using tags?

**Comment by gabegorelick** [comment]
TBH, I'm more concerned with the fact that use of `:latest` will get flagged by scanners, compliance checklists, etc. Pinning to any other (mutable) tag would be fine for me (I have my own processes for pinning to SHAs and vendoring images).

**Comment by ivanstanev** [comment]
Hey @gabegorelick unfortunately for now we cannot change the tag on `busybox:latest` because we also have an Operator for the snyk-monitor. When running on Red Hat, the Operator installs images from Red Hat's container registries. In there there is only a `latest` tag so we can't pin it to a specific version, otherwise we would be breaking the Red Hat Operator installation. We will keep an eye on any changes from Red Hat's side and will do the change whenever possible but for now I'll have to close this!
